CREATE TABLE games_v3 (
	id serial,
	created integer,
	updated integer,
	closed integer,
	name varchar(64),
	dwSize integer,
	dwMaxPlayers integer,
	dwCurrentPlayers integer,
	gameType integer,
	mapname varchar(40),
	hostname varchar(40),
	hostver varchar(64),
	mods varchar(255),
	gvmajor integer,
	gvminor integer,
	private boolean,
	mapmod boolean,
	gameid integer,
	os integer,
	netsum integer,
	hostip inet,
	hostport integer,
	unavail boolean
);
